# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: currency.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63urrency.proto\x12\x08\x63urrency\"9\n\x0bRateRequest\x12\x15\n\rfrom_currency\x18\x01 \x01(\t\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\"\x1d\n\x0cRateResponse\x12\r\n\x05price\x18\x01 \x01(\x01\x32K\n\x0f\x43urrencyService\x12\x38\n\x07GetRate\x12\x15.currency.RateRequest\x1a\x16.currency.RateResponseB\x10Z\x0e\x64\x65mo/server/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016demo/server/pb'
  _globals['_RATEREQUEST']._serialized_start=28
  _globals['_RATEREQUEST']._serialized_end=85
  _globals['_RATERESPONSE']._serialized_start=87
  _globals['_RATERESPONSE']._serialized_end=116
  _globals['_CURRENCYSERVICE']._serialized_start=118
  _globals['_CURRENCYSERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
